require: rubocop-rspec

AllCops:
  DisplayCopNames: true

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

RSpec/MultipleExpectations:
  Max: 2